# Generated by Django 4.2 on 2024-05-14 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_userotp_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userotp',
            old_name='user',
            new_name='email',
        ),
    ]
