# Generated by Django 4.2 on 2024-05-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_rename_user_userotp_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOtp',
        ),
    ]
